"""Persistent, database-independent inference from Groundwork's generated PT files.

The checkpoint supplies a screenshot grounder, not a language-model planner. Only
the application's versioned architecture and preprocessing format are supported.
"""
from __future__ import annotations

import copy
import hashlib
import io
import math
import pickle
import time
from collections.abc import Mapping
from pathlib import Path

import numpy as np
import torch
from PIL import Image, ImageOps, UnidentifiedImageError

from .inference import INFERENCE_LOCK, format_prediction, process_memory_mb
from .ml import (SUPPORTED_ARCHITECTURES, PREPROCESSING, Grounder, Tokenizer,
                 chat_vocabulary_size, generate_chat_reply, preprocess_image)
from .training import CHECKPOINT_SCHEMA, select_device, validate_config


def _threshold(value: float) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value) or not 0 <= value <= 1:
        raise ValueError("Presence threshold must be a finite number between zero and one")
    return float(value)


def _load_file(path: Path, trust_checkpoint: bool) -> tuple[dict, str, str]:
    # Full training checkpoints contain np.random.get_state(), whose uint32
    # array requires these exact NumPy constructors. TorchVersion is stored by
    # run_worker in execution.torch. Never allowlist globals named by the file.
    reconstruct = np._core.multiarray._reconstruct
    safe_types = [reconstruct, (reconstruct, "numpy.core.multiarray._reconstruct"),
                  np.ndarray, np.dtype, type(np.dtype(np.uint32)), torch.torch_version.TorchVersion]
    with path.open("rb") as stream:
        digest = hashlib.file_digest(stream, "sha256").hexdigest()
        stream.seek(0)
        try:
            with torch.serialization.safe_globals(safe_types):
                state = torch.load(stream, map_location="cpu", weights_only=True)
            load_mode = "weights_only"
        except pickle.UnpicklingError as error:
            if not trust_checkpoint:
                raise ValueError(
                    "Safe checkpoint loading failed. Use an inference .pt export generated by Groundwork. "
                    "Only for a file whose source you trust, --trust-checkpoint permits Python pickle loading."
                ) from error
            stream.seek(0)
            state = torch.load(stream, map_location="cpu", weights_only=False)
            load_mode = "trusted_pickle"
    if not isinstance(state, dict):
        raise ValueError("Unsupported checkpoint format: expected a generated checkpoint dictionary")
    return state, digest, load_mode


def _validate_metadata(state: dict) -> tuple[dict, Tokenizer, list[str]]:
    if type(state.get("schema")) is not int or state["schema"] != CHECKPOINT_SCHEMA or not isinstance(state.get("kind"), str) or state["kind"] not in {
        "training_checkpoint", "inference_export", "grounding_chat_training_checkpoint"
    }:
        raise ValueError("Unsupported checkpoint format: select a generated training checkpoint or inference export")
    if state.get("architecture") not in SUPPORTED_ARCHITECTURES or state.get("preprocessing") != PREPROCESSING:
        raise ValueError("Unsupported checkpoint architecture or preprocessing format")
    for key in ("config", "tokenizer", "classes", "model"):
        if key not in state:
            raise ValueError(f"Incomplete checkpoint: missing {key}")
    configuration = state["config"]
    if not isinstance(configuration, dict) or any(not isinstance(key, str) for key in configuration):
        raise ValueError("Checkpoint config must be a dictionary")
    for key in ("image_size", "width", "text_dim", "max_tokens"):
        if key not in configuration:
            raise ValueError(f"Incomplete checkpoint config: missing {key}")
    config = validate_config(configuration)
    tokenizer_data = state["tokenizer"]
    if not isinstance(tokenizer_data, dict):
        raise ValueError("Invalid checkpoint tokenizer")
    vocabulary = tokenizer_data.get("vocabulary")
    max_tokens = tokenizer_data.get("max_tokens")
    if (not isinstance(vocabulary, list) or len(vocabulary) < 2 or
            any(not isinstance(word, str) or not word for word in vocabulary) or
            type(max_tokens) is not int or max_tokens != config["max_tokens"]):
        raise ValueError("Invalid checkpoint tokenizer vocabulary or max_tokens")
    tokenizer = Tokenizer.from_dict(tokenizer_data)
    classes = state["classes"]
    if (not isinstance(classes, list) or not 1 <= len(classes) <= 128 or
            any(not isinstance(name, str) or not name.strip() or len(name) > 80 for name in classes) or
            len(set(classes)) != len(classes)):
        raise ValueError("Invalid checkpoint classes: expected 1 to 128 unique, nonempty class names")
    return config, tokenizer, list(classes)


def _build_model(state: dict, config: dict, tokenizer: Tokenizer, classes: list[str], device: torch.device) -> Grounder:
    values = state["model"]
    if not isinstance(values, Mapping) or any(not isinstance(key, str) for key in values):
        raise ValueError("Invalid model state: expected named weight tensors")
    # Construct shape references without initializing random parameters or
    # allocating a second copy of a potentially large embedding table.
    with torch.device("meta"):
        model = Grounder(len(tokenizer.vocabulary), len(classes), config, chat_vocabulary_size(state))
    expected = model.state_dict()
    if set(values) != set(expected):
        missing, extra = sorted(set(expected) - set(values)), sorted(set(values) - set(expected))
        raise ValueError(f"Invalid model state: missing tensors {missing}; unexpected tensors {extra}")
    for name, value in values.items():
        reference = expected[name]
        if (not isinstance(value, torch.Tensor) or value.layout != torch.strided or
                value.shape != reference.shape or value.dtype != reference.dtype or value.device.type != "cpu"):
            raise ValueError(f"Invalid model tensor {name}: shape, dtype, or layout does not match the architecture")
        if not bool(torch.isfinite(value).all()):
            raise ValueError(f"Invalid model tensor {name}: weights must be finite")
    model.load_state_dict(values, strict=True, assign=True)
    return model.to(device).eval()


def _validate_output(output: dict, class_count: int) -> None:
    if not isinstance(output, dict):
        raise ValueError("Model returned invalid output; no target can be used")
    for name, shape in (("bbox", (1, 4)), ("presence_logits", (1,)), ("class_logits", (1, class_count))):
        value = output.get(name)
        if not isinstance(value, torch.Tensor) or tuple(value.shape) != shape or not bool(torch.isfinite(value).all()):
            raise ValueError(f"Model returned invalid or non-finite {name}; no target can be used")
    box = output["bbox"][0]
    if not bool(((box >= 0) & (box <= 1)).all()) or not bool((box[:2] < box[2:]).all()):
        raise ValueError("Model returned an invalid normalized bounding box; no target can be used")


class FileGrounder:
    """Load a generated model once and predict from PNG viewport captures.

    No run ID, API server, SQLite database, network access, or training data is
    required. ``auto`` uses CUDA when available; ``cpu`` explicitly overrides the
    device saved during training. A requested but unavailable CUDA device fails
    clearly instead of silently changing execution mode.
    """

    def __init__(self, path: str | Path, device: str = "auto", threshold: float = 0.5,
                 trust_checkpoint: bool = False):
        self.threshold = _threshold(threshold)
        if device not in {"auto", "cpu", "cuda"}:
            raise ValueError("Device must be auto, cpu, or cuda")
        if not isinstance(trust_checkpoint, bool):
            raise ValueError("trust_checkpoint must be a boolean")
        self.path = Path(path).expanduser().resolve()
        if self.path.suffix.lower() != ".pt" or not self.path.is_file():
            raise ValueError(f"Checkpoint must be an existing .pt file: {self.path}")
        self.device = select_device({"device": device})
        started = time.perf_counter()
        with INFERENCE_LOCK:
            try:
                state, digest, load_mode = _load_file(self.path, trust_checkpoint)
            except (OSError, EOFError, RuntimeError, pickle.UnpicklingError) as error:
                raise ValueError(f"Unable to read generated .pt checkpoint: {error}") from error
            self.config, self.tokenizer, self.classes = _validate_metadata(state)
            self.model = _build_model(state, self.config, self.tokenizer, self.classes, self.device)
            self.chat_tokenizer = copy.deepcopy(state.get("chat_tokenizer"))
        # Retain inference data only; optimizer, RNG, and other training state are
        # released once initialization returns.
        self._metadata = {
            "architecture": state["architecture"], "preprocessing": state["preprocessing"],
            "classes": self.classes, "config": self.config, "kind": state["kind"], "schema": state["schema"],
            "checkpoint": self.path.name, "checkpoint_path": str(self.path), "checkpoint_sha256": digest,
            "checkpoint_size_bytes": self.path.stat().st_size, "run_id": state.get("run_id"),
            "device": str(self.device), "load_mode": load_mode,
            "vocabulary_size": len(self.tokenizer.vocabulary), "load_latency_ms": (time.perf_counter() - started) * 1000,
            "capabilities": ["grounding", "chat"] if self.chat_tokenizer else ["grounding"],
            "score_description": "Target-presence score; not a calibrated click-success probability",
        }

    @property
    def metadata(self) -> dict:
        return copy.deepcopy(self._metadata)

    def chat(self, message: str) -> dict:
        """Generate a reply using the same loaded model used by ``predict``."""
        if self.chat_tokenizer is None:
            raise ValueError("This grounding model has not been trained for chat yet")
        with INFERENCE_LOCK:
            return {**generate_chat_reply(self.model, self.chat_tokenizer, message),
                    "run_id": self._metadata["run_id"], "checkpoint": self.path.name}

    def predict(self, png_bytes: bytes, instruction: str, threshold: float | None = None) -> dict:
        chosen_threshold = self.threshold if threshold is None else _threshold(threshold)
        if not isinstance(instruction, str) or not instruction.strip():
            raise ValueError("A nonempty grounding instruction is required")
        if not isinstance(png_bytes, bytes) or not png_bytes:
            raise ValueError("A PNG screenshot as nonempty bytes is required")
        with INFERENCE_LOCK:
            if self.device.type == "cuda":
                torch.cuda.reset_peak_memory_stats(self.device)
                torch.cuda.synchronize(self.device)
            started = time.perf_counter()
            try:
                with Image.open(io.BytesIO(png_bytes)) as opened:
                    if opened.format != "PNG":
                        raise ValueError("Browser screenshot must be a PNG image")
                    oriented = ImageOps.exif_transpose(opened)
                    width, height = oriented.size
                    images = preprocess_image(oriented, self.config["image_size"]).unsqueeze(0).to(self.device)
            except (UnidentifiedImageError, OSError, Image.DecompressionBombError) as error:
                raise ValueError(f"Unable to decode the PNG screenshot: {error}") from error
            ids, length = self.tokenizer.encode(instruction)
            with torch.inference_mode():
                output = self.model(images, torch.tensor([ids], device=self.device),
                                    torch.tensor([length], device=self.device))
            if self.device.type == "cuda":
                torch.cuda.synchronize(self.device)
            latency = (time.perf_counter() - started) * 1000
            _validate_output(output, len(self.classes))
            gpu_memory = torch.cuda.max_memory_allocated(self.device) / 2**20 if self.device.type == "cuda" else 0.0
            rss = process_memory_mb()
            result = format_prediction(output, 0, width, height, self.classes, chosen_threshold, instruction,
                                       latency, gpu_memory if self.device.type == "cuda" else rss)
            result.update(
                run_id=self._metadata["run_id"], checkpoint=self.path.name, checkpoint_path=str(self.path),
                checkpoint_sha256=self._metadata["checkpoint_sha256"], kind=self._metadata["kind"],
                device=str(self.device), preprocessing=PREPROCESSING, image_size=self.config["image_size"],
                gpu_peak_allocated_mb=gpu_memory, process_rss_mb=rss,
                latency_scope="image decode, preprocessing, device transfer, and forward; excludes model loading",
                unknown_words=sorted({word for word in self.tokenizer.words(instruction) if word not in self.tokenizer.lookup}),
            )
            return result
